### ISSUE TITLE
Report filename with invalid encoding

### ISSUE THREAD

**Issue by ezyang** [facebook/codemod#112]
I'm trying to run codemod on my codebase and it is choking with:

```
Traceback (most recent call last):
  File "/home/ezyang/local/pytorch-tmp-env/bin/codemod", line 8, in <module>
    sys.exit(main())
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.7/site-packages/codemod/base.py", line 1025, in main
    run_interactive(**options)
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.7/site-packages/codemod/base.py", line 167, in run_interactive
    for patch in suggestions:
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.7/site-packages/codemod/base.py", line 442, in generate_patches
    lines = list(open(path))
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 16: invalid continuation byt
```

It would be very nice if it told me what file had the bad encoding!

**Comment by kir0ul** [comment]
I have the exact same problem :slightly_frowning_face:

**Comment by donnlee** [comment]
As workaround, I did:

```
   git clone https://github.com/facebook/codemod.git
   cd codemod/
   python setup.py install --user
```
because there was a patch made in #93 that is not in the PyPi (pip install ...) version.
