### ISSUE TITLE
Running codemod.py without any params results in an error

### ISSUE THREAD

**Issue by jayanthm** [facebook/codemod#49]
It also seems to cause this for a few other seemingly ok inputs.
> $ codemod.py
Searching for first instance...
Traceback (most recent call last):
  File "/usr/local/bin/codemod.py", line 853, in <module>
    run_interactive(**options)
  File "/usr/local/bin/codemod.py", line 129, in run_interactive
    for patch in suggestions:
  File "/usr/local/bin/codemod.py", line 357, in generate_patches
    path_list = Query._walk_directory(self.root_directory)
  File "/usr/local/bin/codemod.py", line 395, in _walk_directory
    for root, dirs, files in os.walk(root_directory)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 276, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by modocache** [comment]
Thanks for the report! :+1:

We could definitely use some tests around the command-line interface.

**Comment by modocache** [comment]
This should have been fixed by #51. Can you confirm, @jayanthm? :dart:

**Comment by jayanthm** [comment]
@modocache Fixed!
