### ISSUE TITLE
Unicode crash should be handled gracefully

### ISSUE THREAD

**Issue by adamjernst** [facebook/codemod#93]
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/codemod", line 9, in <module>
    load_entry_point('codemod==1.0.0', 'console_scripts', 'codemod')()
  File "/opt/homebrew/lib/python3.5/site-packages/codemod/base.py", line 1025, in main
    run_interactive(**options)
  File "/opt/homebrew/lib/python3.5/site-packages/codemod/base.py", line 167, in run_interactive
    for patch in suggestions:
  File "/opt/homebrew/lib/python3.5/site-packages/codemod/base.py", line 442, in generate_patches
    lines = list(open(path))
  File "/opt/homebrew/Cellar/python35/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 130: invalid continuation byte
```

**Comment by adamjernst** [comment]
Best to skip files with unicode errors, instead of failing entirely.

**Comment by attilammagyar** [comment]
This comment might not be very constructive, but as a workaround, the following can handle encoding issues better, it covers most use cases of `codemod`, and it offers much greater flexibility both in the file search and in the modifications:

    find src/ -name '*.html' \
        | xargs \
            sed -ri 's|<(/?)p( [^>]*)?>|<\1div\2>|g'
    git add -p src/

To be a little bit more constructive, I'd suggest doing some or all of the following:
 * add an `--encoding` option so that Python would know what it has to deal with
 * add a `--binary` option which would open the files as binary, and also convert the pattern and the replacement to `bytes` as well to make `re` happy
 * if a file still has to be skipped due to some error, then at least print a warning to the user so that problematic files don't go unnoticed
